from __future__ import annotations

import json
import re

from .contract_details import contract_details_for_channel
from .model import ArchFlowAst, Channel


def contract_id(channel: Channel) -> str:
    raw = f"{channel.source}__{channel.via}__{channel.target}"
    return re.sub(r"[^A-Za-z0-9_]+", "_", raw)


def json_schema_for_channel(channel: Channel) -> dict:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": contract_id(channel),
        "type": "object",
        "description": channel.schema or f"TODO: define .Schema.{channel.via}",
        "additionalProperties": True,
        "properties": {
            "traceId": {
                "type": "string",
                "description": "Correlation id for this isolated channel message.",
            },
            "payload": {
                "type": "object",
                "description": channel.schema or "Channel payload.",
                "additionalProperties": True,
            },
        },
        "required": ["traceId", "payload"],
    }


def mock_payload_for_channel(channel: Channel) -> dict:
    return {
        "traceId": f"mock-{contract_id(channel).lower()}",
        "payload": {
            "channel": channel.via,
            "from": channel.source,
            "to": channel.target,
            "description": channel.schema or f"TODO: define .Schema.{channel.via}",
        },
    }


def generate_typescript_contracts(ast: ArchFlowAst) -> str:
    lines = [
        "// Generated by ArchFlow MVP. Edit the .af source, not this file.",
        "",
        "export interface ArchFlowMessage<TPayload extends Record<string, unknown> = Record<string, unknown>> {",
        "  traceId: string;",
        "  payload: TPayload;",
        "}",
        "",
    ]
    for channel in ast.channels:
        name = _type_name(channel)
        lines.extend(
            [
                f"export type {name} = ArchFlowMessage<{{",
                "  [key: string]: unknown;",
                "}>;",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def generate_typescript_assembly(ast: ArchFlowAst) -> str:
    lines = [
        "// Generated assembly sketch for ArchFlow isolated channels.",
        "import type { ArchFlowMessage } from './contracts';",
        "",
        "type Handler = (message: ArchFlowMessage) => Promise<void> | void;",
        "",
        "class InMemoryChannel {",
        "  private handlers = new Map<string, Handler[]>();",
        "",
        "  on(channel: string, handler: Handler) {",
        "    const handlers = this.handlers.get(channel) ?? [];",
        "    handlers.push(handler);",
        "    this.handlers.set(channel, handlers);",
        "  }",
        "",
        "  async send(channel: string, message: ArchFlowMessage) {",
        "    for (const handler of this.handlers.get(channel) ?? []) {",
        "      await handler(message);",
        "    }",
        "  }",
        "}",
        "",
        "const bus = new InMemoryChannel();",
        "",
    ]
    for channel in ast.channels:
        channel_key = contract_id(channel)
        lines.extend(
            [
                f"bus.on('{channel_key}', async (message) => {{",
                f"  // TODO: route [{channel.via}] from @{channel.source} to @{channel.target}.",
                "  void message;",
                "});",
                "",
            ]
        )
    lines.append("export { bus };")
    return "\n".join(lines).rstrip() + "\n"


def graph_mermaid(ast: ArchFlowAst) -> str:
    lines = ["flowchart TD"]
    for channel in ast.channels:
        lines.append(f"  {channel.source}[\"@{channel.source}\"] -->|\"{channel.via}\"| {channel.target}[\"@{channel.target}\"]")
    return "\n".join(lines) + "\n"


def contracts_manifest(ast: ArchFlowAst) -> dict:
    return {
        contract_id(channel): {
            "source": channel.source,
            "target": channel.target,
            "via": channel.via,
            "schema": json_schema_for_channel(channel),
            "details": contract_details_for_channel(ast, channel),
            "mock": mock_payload_for_channel(channel),
        }
        for channel in ast.channels
    }


def dumps_json(data: object) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _type_name(channel: Channel) -> str:
    return "".join(part[:1].upper() + part[1:] for part in contract_id(channel).split("_") if part) + "Message"
