// Generated by ArchFlow MVP. Edit the .af source, not this file.

export interface ArchFlowMessage<TPayload extends Record<string, unknown> = Record<string, unknown>> {
  traceId: string;
  payload: TPayload;
}

export type ClientUITaskAPITaskBackendMessage = ArchFlowMessage<{
  [key: string]: unknown;
}>;

export type TaskBackendTaskEventsNotificationWorkerMessage = ArchFlowMessage<{
  [key: string]: unknown;
}>;
